CommitMsg:
  CapitalizedSubject:
    enabled: false

  EmptyMessage:
    enabled: false

  TrailingPeriod:
    enabled: true

  TextWidth:
    enabled: false

PreCommit:
  ALL:
    on_warn: fail

  AuthorEmail:
    enabled: true

  AuthorName:
    enabled: true

  MergeConflicts:
    enabled: true

  YamlSyntax:
    enabled: true

  BundleCheck:
    enabled: true

  PreCommit:
    RuboCop:
      enabled: true

    Fasterer:
      enabled: true

    BundleAudit:
      enabled: true

    Reek:
      enabled: true
    RailsBestPractices:
      enabled: true

    Foodcritic:
      enabled: true
      cookbooks_directory: ‘site-cookbooks’
      environments_directory: ‘environments’
      roles_directory: ‘roles’
      include:
        - ‘site-cookbooks/**/*’
        - ‘environments/**/*’
        - ‘roles/**/*’
